baseurl = "http://workers-safety.ca.s3-website-us-east-1.amazonaws.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-universal-theme"
title = "Legal Clinic"
[Permalinks]
blog = "/blog/:year/:month/:day/:filename/"
[params]
Title = "Workers Legal Clinic"
about_us = "<p>Workers Safety and Health Legal Clinic.</p>"
address = "<p><strong>Health and Safety Legal Clinic</strong>\r\n        <br>Monday - Friday 9am - 5pm\r\n        <br>Closed on public holidays\r\n        <br>180 Dunas St. West\r\n        <br>Suite 2000, Box 4\r\n        <br>Toronto, ON\r\n        <br>M5G 1Z8\r\n        <br>\r\n        <strong>Canada</strong>\r\n      </p>\r\n      "
author = "Workers"
copyright = "Copyright (c) 2015 - 2016, WSHLC; all rights reserved."
date_format = "2006-01-02T00:00:00+00:00"
email = "berenice@cotero.org"
logo = "img/logo.png"
viewMorePostLink = "/blog/"
[params.carousel]
enable = true
[params.clients]
enable = true
subtitle = ""
title = "Our Clients"
[params.features]
enable = true
[params.recent_posts]
enable = true
subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
title = "From our blog"
[params.see_more]
enable = true
icon = "fa fa-file-code-o"
link_text = "Check other homepages"
link_url = "http://workers-safety.ca"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
title = "Do you want to see more?"
[params.testimonials]
enable = true
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
title = "Testimonials"
[params.widgets]
categories = true
search = true
tags = true
